name: Generate Github Pages from ASCIIDoc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: asciidoctor-ghpages
        uses: manoelcampos/asciidoctor-ghpages-action@v2