name: Generate Github Pages from ASCIIDoc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkout-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build ASCIIDoc with Gradle
        run: ./gradlew clean asciidoctor
      - name: Simple deploy with git
        uses: rdarida/simple-github-pages-deploy-action@v1
        with:
          git-base-folder: build/docs/asciidoc/en/